name: Build and Test
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

env:
  HELLO_STRING: ${{ 'Hi, this is lijiu!' }}

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache local Maven repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-2-
      - name: Maven Build
        run: |
          mvn clean package install -DskipTests

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Maven Test
        run: |
          mvn test
  
  Test_Report:
    if: ${{ always() }}
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: All Test Result
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit
          max-annotations: '50'
      - name: Surefire Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Error Test Report
          report_paths: target/surefire-reports/TEST-*.xml



  
    
