name: Remote Test
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        env:
          P_GITHUB_REPOSITORY: ${{ github.repository }}
          P_GITHUB_REF: ${{ github.ref }}
          P_GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "id:${{ github.run_id }} repository:$P_GITHUB_REPOSITORY ref:$P_GITHUB_REF sha:$P_GITHUB_SHA"
      - uses: actions/checkout@v2
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          port: ${{ secrets.ECS_PORT }}
          key: ${{ secrets.ECS_KEY }}
          source: "pom.xml"
          target: "/home/lzw"
