name: Remote Test
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        env:
          P_GITHUB_REPOSITORY: ${{ github.repository }}
          P_GITHUB_REF: ${{ github.ref }}
          P_GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "id:${{ github.run_id }} ${{ github.run_attempt }} repository:$P_GITHUB_REPOSITORY ref:$P_GITHUB_REF sha:$P_GITHUB_SHA"
      - uses: actions/checkout@v2
      - name: host
        env:
          thost: ${{ secrets.ECS_HOST }}
        run: |
          echo "host: $thost"
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          password: ${{ secrets.ECS_PASSWORD }}
          port: ${{ secrets.ECS_PORT }}
          script: |
            ls /home/lzw
            ll /home/lzw
    

