name: Remote Test
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  Remote_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        env:
          P_GITHUB_REPOSITORY: ${{ github.repository }}
          P_GITHUB_REF: ${{ github.ref }}
          P_GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "id:${{ github.run_id }} ${{ github.run_attempt }} repository:$P_GITHUB_REPOSITORY ref:$P_GITHUB_REF sha:$P_GITHUB_SHA"
          pwd
      - uses: actions/checkout@v2
      - name: Remote Run Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          password: ${{ secrets.ECS_PASSWORD }}
          port: ${{ secrets.ECS_PORT }}
          script: |
            ls -l /home/lzw
      - name: Get Test Report Files
        run: |
          pwd
          sshpass -p ${{ secrets.ECS_PASSWORD }} scp -r -o StrictHostKeyChecking=no -P ${{ secrets.ECS_PORT }} root@${{ secrets.ECS_HOST }}:/home/lzw/surefire-reports .
      - name: All Test Result
        uses: dorny/test-reporter@v1
        with:
          name: All Test Result
          path: surefire-reports/TEST-*.xml
          reporter: java-junit
          max-annotations: '50'
      - name: Error Test Report
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Error Test Report
          report_paths: surefire-reports/TEST-*.xml
    

