name: Remote Test
on:
  push:
    branches:
      - "main"
    #paths-ignore:
    #  - "README.md"
  pull_request_target:
    types: [labeled]
    branches:
      - "main"
    #paths-ignore:
    #  - "README.md"

jobs:
  Remote_Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: print
        run: |
          echo "state:${{ github.event.review.state }}"
      - uses: actions/checkout@v2
      - name: Deploy PolarDB-X Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          #password: ${{ secrets.ECS_PASSWORD }}
          key: ${{ secrets.ECS_KEY }}
          port: ${{ secrets.ECS_PORT }}
          command_timeout: 60m
          script: |
            cd workspace
            ls
