name: Remote Test
on:
  push:
    branches:
      - "main"
    #paths-ignore:
    #  - "README.md"
  pull_request:
    branches:
      - "main"
    #paths-ignore:
    #  - "README.md"

jobs:
  Remote_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy PolarDB-X Cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          #password: ${{ secrets.ECS_PASSWORD }}
          key: ${{ secrets.ECS_KEY }}
          port: ${{ secrets.ECS_PORT }}
          envs: TEST_UID,GIT_URL,COMMIT_ID,CODE_REF
          command_timeout: 60m
          script: |
            cd workspace
            ls
    

